# * verify image:
#? $ docker pull catthehacker/ubuntu:custom-20.04
# * run:
#? E:\apps\act.exe -j local -s GITHUB_TOKEN="$(gh auth token)" --pull=false -P ubuntu-latest=catthehacker/ubuntu:custom-20.04-20231229  --no-cache-server
name: locally test api
on:
  repository_dispatch:
    types: [local]

permissions:
  contents: write

jobs:
  local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 👀 docker network
        run: |
          docker network ls
          docker network ls | grep jamon && docker network rm jamon
          docker network create jamon
          docker image ls

      # - name: build docker
      # todo: can we cache an image on GH❓
      # todo: can we avoid unnecesary rebuilds (f.i. with hash tag)❓
      # run: docker buildx build --tag rustiko:chef --file dockerfile.ga .

      - name: server
        run: docker run --rm --detach -p 4560:4560 --name server --network jamon rustiko:chef

      - name: wait a bit
        run: sleep 15

      - name: sqld
        run: docker run --rm --detach -p 8080:8080 --name sqld -e RUST_LOG=sqld=debug,info --network jamon ghcr.io/tursodatabase/libsql-server:main

      - name: install hurl
        run: |
          VERSION=4.1.0
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/$VERSION/hurl_${VERSION}_amd64.deb
          sudo apt update && sudo apt install ./hurl_${VERSION}_amd64.deb

      - name: 🧪 test api
        run: hurl --test api.hurl

      - name: 👀 network logs
        run: |
          ss -natup
          echo '==== 😏'
          netstat -natup
          ls -lahrt .
          ps -aux

      - name: Dump sqld logs and stop
        if: always()
        run: |
          docker logs sqld
          docker ps
          docker ps | grep sqld && docker kill sqld
          docker ps | grep server && docker kill server
          # if below line is at the beginning it will fail locally
          docker network ls | grep jamon && docker network rm jamon
